name: tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: true
        matrix:
          php: [ 8.1, 8.2, 8.3 ]
          stability: [ prefer-lowest, prefer-stable ]
          include:
            - php: 8.1
              stability: prefer-lowest
              phpunit: 10
            - php: 8.1
              stability: prefer-stable
              phpunit: 10
            - php: 8.2
              stability: prefer-lowest
              phpunit: 10
            - php: 8.2
              stability: prefer-stable
              phpunit: 10
            - php: 8.3
              stability: prefer-lowest
              phpunit: 11
            - php: 8.3
              stability: prefer-stable
              phpunit: 11
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          cache_dir=$(composer config cache-files-dir)
          echo "dir=$cache_dir" >> $GITHUB_ENV

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.dir }}
          key: ${{ runner.os }}-composer-php-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, gd
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Require specific versions of packages
        run: composer update phpunit/phpunit:^${{ matrix.phpunit }} --dev -W

      - name: Lint code
        run: composer lint

      - name: Run PHPStan
        run: composer phpstan

      - name: Execute tests
        run: composer test
